# Docker compose file to run the API on the server
# using the latest deployed image from Docker Hub

services:
  pkrddit:
    image: kinp/stravarts:latest
    ports:
      - "5400:5400"
    env_file:
      - .env
    restart: always
